"""empty message

Revision ID: 7f08b487b4d8
Revises: bfe646b34128
Create Date: 2018-09-30 14:15:48.779672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f08b487b4d8'
down_revision = 'bfe646b34128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('telephone', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telephone')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
